version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9-browsers

    working_directory: ~/repo
    environment:
      # MOCHA_REPORTER: --reporter mocha-junit-reporter
      # MOCHA_FILE: $CIRCLE_TEST_REPORTS/junit/test-results.xml

    store_test_results:
      path: junit

    steps:
      - checkout

      Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "javascript/visual-testing/package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd javascript/visual-testing && npm install

      - save_cache:
          paths:
            - cd javascript/visual-testing/node_modules
          key: v1-dependencies-{{ checksum "javascript/visual-testing/package-lock.json" }}

      - run: cd javascript/visual-testing && npm test
